Library_Management_System_MVC/Controllers/AuthorController.cs
using Library_Management_System_MVC.Models;
using Library_Management_System_MVC.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Library_Management_System_MVC.Controllers
{
    public class AuthorController : Controller
    {

        public static List<Author> Authors = new List<Author>
        {
            new Author {Id = 1, FirstName = "Lev", LastName = "Tolstoy", DateOfBirth = new DateTime(1828, 9, 9) },
            new Author {Id = 2, FirstName = "Virginia", LastName = "Woolf", DateOfBirth = new DateTime(1882, 1, 25) },
            new Author {Id = 3, FirstName = "Erich", LastName = "Fromm", DateOfBirth = new DateTime(1900, 3, 23) }
        };
       

        //Tüm yazarların listelendiğii action (Author/list.cshtml'de görüntülenecek)
        public IActionResult List() //Yalnızca yazarların listesini döndürecek
        {
            var authorList = Authors.Where(a=> !a.IsDeleted) //Sadece Silinmemiş yazarlar.
                                    .ToList();      
            return View(authorList); //List.cshtml view'ına yazar listesi gönderiyoruz.
        }

        //Tek bir yazarın detaylarının gösterildiği action
        public IActionResult Details(int id)
        {
            //Parametredeki id'ye sahip yazarları bulacağız
            var author = Authors.FirstOrDefault(a => a.Id == id);
            if (author == null)
                return NotFound();

            var books = BookController.Books.Where(b => b.AuthorId == id).ToList();

            var viewModel = new AuthorDetailViewModel
            {
                FirstName = author.FirstName,
                LastName = author.LastName,
                DateOfBirth = author.DateOfBirth,
                Author = author,
                Books = books
            };
            return View(viewModel);

            //FirstOrDefault listenin içinden ilk uygun elemanı bulur. 
            //a => a.Id == id her bir yazar için Id değeri verilen id'ye eşit mi diye kontrol eder. Bu şarta ilk uyan yarar author değişkenine atanır.
        }

        //Yeni yazar eklemek için formu gösterecek (GET)
        [HttpGet]
        public IActionResult Create()
        {
            return View(); //Create.cshtml view'unu dönecek
        }

        //Yeni yazar ekleme işlemi yapacağız (POST)
        [HttpPost]
        public IActionResult Create(Author author)
        {
            //Yeni yazara otomatik Id atayacak (varsa en yükssek id'nin 1 fazlası)
            author.Id = Authors.Count > 0 ? Authors.Max(a => a.Id) + 1 : 1; // Eğer listede yazar varsa Authors.Count, ?'den sonra koşul doğruysa çalışacak ifade bulunuyor. Bu ifade de Mevcut yazarların en büyük Id'sini buluyor ve 1 ekliyor. Eğer Koşul doğru değilse :'dan sonra çalışacak ifade bulunuyor. yani 1 yazacağız. 
            Authors.Add(author); //Yazarı listeye ekleyeccek
            return RedirectToAction("List"); //Listeye yönlendirecek
        }

        //Var olan yazarın düzenleme formunu gösterir. (GET)
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var author = Authors.FirstOrDefault(a => a.Id == id);
            if (author == null)
                return NotFound();
            return View(author);
        }

        //Yazar düzenleme işlemini kaydeder (POST)

        [HttpPost]
        public IActionResult Edit(Author updatedAuthor)
        {
            //Düzenlenen yazarı listeden bulur
            var author = Authors.FirstOrDefault(a => a.Id == updatedAuthor.Id);
            if (author != null) //Eğer author null değilse
            {
                //Alanları yeni değerlerle günceller.
                author.FirstName = updatedAuthor.FirstName;
                author.LastName = updatedAuthor.LastName;
                author.DateOfBirth = updatedAuthor.DateOfBirth;
            }

            return RedirectToAction("List"); //Listeye döner
        }

        //Yazar silme onay sayfasını gösterecek (GET)
        //Get veriyi çeker/Gösterir, okur
        [HttpGet]
        public IActionResult Delete(int id) 
        {
            //Silinecek yazarı bulur

            var author = Authors.FirstOrDefault( a => a.Id == id);
            return View(author);
        }

        //Yazar silme işlemi (POST)
        //[HttpPost]: sadece POST isteklerinde çalışıyor.
        //[ActionName("Delete")]: Bu metoda URL ve View'da "Delete" adıyla ulaşmayı sağlıyor.

        [HttpPost, ActionName("Delete")]
        //Bu kısımda yazar gerçekten silinir.
        //POST Veriyi değiştirir (ekleme/silme/güncelleme).
        public IActionResult DeleteConfirmed(int id)
        {
            var author = Authors.FirstOrDefault(a => a.Id == id); //Yine silinecekleri seçiyoruz.
            if (author != null) //Eğer authhor null değilse
            {
                author.IsDeleted = true; //Yazarı listeden çıkarır
            }
            return RedirectToAction("List"); //listeye döner.
        }

        public IActionResult DeletedList()
        {
            var deletedAuthors = Authors.Where(a=> a.IsDeleted).ToList();
            return View(deletedAuthors);
        }

        public IActionResult Restore(int id)
        {
            var author = Authors.FirstOrDefault(a => a.Id == id);
            if (author != null)
                author.IsDeleted = false;
            return RedirectToAction("DeletedList");

        }
    }
}

Library_Management_System_MVC/Controllers/BookController.cs
using Library_Management_System_MVC.Models;
using Library_Management_System_MVC.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Net.WebSockets;

namespace Library_Management_System_MVC.Controllers
{
    public class BookController : Controller
    {

        public static List<Book> Books = new List<Book>
        {
            new Book { Id = 1, Title = "Savaş ve Barış", AuthorId = 1, Genre = "Roman", PublishDate = new DateTime(1867, 1, 1), ISBN = "978-975-05-1232-2", CopiesAvailable =1 },
            new Book {Id = 2, Title = "Orlando", AuthorId = 2, Genre = "Roman", PublishDate = new DateTime(1928, 10, 11), ISBN = "978-605-4927-65-4", CopiesAvailable = 1 },
            new Book { Id = 3, Title = "Marx'ın İnsan Anlayışı", AuthorId = 3, Genre = "Felsefe", PublishDate = new DateTime(1961, 1, 1), ISBN = "978-605-02-0366-0", CopiesAvailable = 1}


        };

        //Kitapların listesini gösteren action (Book/List.cshtml'de görüntülenir.
        public IActionResult List()
        {
            //Her kitao için yazar bilgisini AuthorController'dan alır.
            var bookList = Books.Where(b => !b.IsDeleted).Select(b => new BookDetailViewModel
            {
                Book = b,
                Author = AuthorController.Authors.FirstOrDefault(a => a.Id == b.AuthorId)
            }).ToList();

            if (bookList == null)
                bookList = new List<BookDetailViewModel>();
            return View(bookList);
        }

        //Belirli bir kitabın detayını gösteriyor
        public IActionResult Details(int id)
        {
            //Books listesinde id'si verilen kitabı buluyorum
            var book = Books.FirstOrDefault(b => b.Id == id);

            //Bu kitabın yazarını, AuthorController.Authors listesinden buluyorum
            var author = AuthorController.Authors.FirstOrDefault(a => a.Id == book.AuthorId);

            //Hem kitabı hem yazarı BookDetailViewModel adlı bir nesneye doldurduk.
            var viewModel = new BookDetailViewModel
            {
                Book = book,
                Author = author
            };
            return View(viewModel); //Details.cshtml view'ine gönderir.
        }

        //Yeni kitap ekleme formu (GET olacak)
        [HttpGet]
        public IActionResult Create()
        {
            //Yazarları dropdown olarak gösterebilmek için ViewBag ile yazar listesini gönderecek
            ViewBag.Authors = AuthorController.Authors;
            //ViewBag Controller'dan geçici olarak veri göndermek için kullanılır. Controller'da yazar listesini ViewBag ile View'a taşıyoruz.
            return View();
        }

        [HttpPost]
        public IActionResult Create(Book book)
        {
            //Id'yi otomaik belirleyecek. b.Id'yi seçtiğimizde eğer Books.Count sıfırdan büyükse Books.Max'ı seçecek ve en büyük Id'ye 1 ekleyecek, Eğer hiç books yoksa 1 olarak atayacak.
            book.Id = Books.Count > 0 ? Books.Max(b => b.Id) + 1 : 1;

            Books.Add(book);
            return RedirectToAction("List");
        }


        //Var olan kitabın düzenleme formunu gösterir. (GET)
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var book = Books.FirstOrDefault(b => b.Id == id);
            ViewBag.Authors = AuthorController.Authors;
            return View(book);
        }

        //POST
        [HttpPost]
        public IActionResult Edit(Book updatedBook)
        {
            var book = Books.FirstOrDefault(b => b.Id == updatedBook.Id);
            if (book != null)
            {
                //Alanları yeni değerlerle güncelliyoruz
                book.Title = updatedBook.Title;
                book.AuthorId = updatedBook.AuthorId;
                book.Genre = updatedBook.Genre;
                book.PublishDate = updatedBook.PublishDate;
                book.ISBN = updatedBook.ISBN;
                book.CopiesAvailable = updatedBook.CopiesAvailable;

            }

            return RedirectToAction("List");
        }


        //Kitap silme onay sayfası
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var book = Books.FirstOrDefault(b => b.Id == id);
            return View(book);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var book = Books.FirstOrDefault(b => b.Id == id);

            if (book != null)
            {
                book.IsDeleted = true;
            }
            return RedirectToAction("List");
        }

        public IActionResult DeletedList()
        {
            var deletedBooks = Books.Where(b => b.IsDeleted)
                                    .Select(b => new BookDetailViewModel
                                    {
                                        Book = b,
                                        Author = AuthorController.Authors.FirstOrDefault(a => a.Id == b.AuthorId)
                                    }).ToList();
            return View(deletedBooks);

        }

       public IActionResult Restore(int id)
        {
            var book = Books.FirstOrDefault(b=>b.Id == id);
            if (book != null)
                book.IsDeleted = false;
            return RedirectToAction("DeletedList");
        }

    }
}

Library_Management_System_MVC/Views/Shared/_FooterPartial.cshtml
<footer class="border-top footer text-muted text-center py-2 fixed-bottom bg-white" style="z-index: 999;">
    © 2025 - Kütüphane Yönetim Sistemi | Tüm hakları saklıdır - Halenur Gürel
</footer>

Library_Management_System_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kütüphane Yönetim Sistemi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Library_Management_System_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand d-flex align-items-center gap-2" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/library.png" alt="Logo" height="36" class="d-inline-block align-text-top" />
                    Kütüphane Yönetim Sistemi
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">Hakkında</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="List">Kitaplar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="List">Yazarlar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @await Html.PartialAsync("_FooterPartial")

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
</body>
</html>